# Generated by Django 4.2.6 on 2023-11-06 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0007_articleimage_remove_article_image_article_images'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='images',
        ),
        migrations.AddField(
            model_name='article',
            name='image',
            field=models.ImageField(default='swift.jpg', upload_to='articles/'),
        ),
        migrations.DeleteModel(
            name='ArticleImage',
        ),
    ]
