# Generated by Django 4.2.6 on 2023-11-07 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0010_remove_article_image_article_media_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='media_file',
            field=models.FileField(blank=True, default='swift.jpg', null=True, upload_to='media/'),
        ),
    ]
