# Generated by Django 4.2.6 on 2023-11-07 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0011_alter_article_media_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='media_file',
        ),
        migrations.AddField(
            model_name='article',
            name='image',
            field=models.ImageField(default='swift.jpg', upload_to='articles/'),
        ),
    ]
